### ISSUE TITLE
Formatting problem with TimeZones 

### ISSUE THREAD

**Issue by Herold1989** [micahjsmith/FredData.jl#16] opened 2020-01-27 13:35 UTC
After upgrading to Julia 1.3.1 yesterday, I encountered the following error while trying to fetch the US GDP series from FRED:

```
MethodError: Cannot convert an object of type TimeZones.ZonedDateTime to an object of type DateTime
Closest candidates are:
 convert(::Type{DateTime}, !Matched::Date) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Dates/src/conversions.jl:30
 convert(::Type{DateTime}, !Matched::Millisecond) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Dates/src/conversions.jl:34
 convert(::Type{DateTime}, !Matched::PyCall.PyObject) at /Users/jensherold/.julia/packages/PyCall/ttONZ/src/pydates.jl:135
 ...
DateTime(::TimeZones.ZonedDateTime) at conversions.jl:20
(::FredData.var"#parse_last_updated#4")(::String) at get_data.jl:82
#get_data#3(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(get_data), ::Fred, ::String) at get_data.jl:84
get_data(::Fred, ::String) at get_data.jl:34
top-level scope at hp_filter_us_gdp_FRED_pull.jl:7
```

This is my minimum working example:

```
using FredData

f = Fred()
Fred_Key  = "GDPC1"
pull_data = get_data(f, Fred_Key)
```

I am running this code on Juno in Atom using FredData version v0.3.1

Any help/ideas is appreciated.

Best,

Jens

**Comment by fratrik** [comment] 2020-02-04 02:41
I think if you type 

```
> dev https://github.com/fratrik/FredData.jl.git
```

It will work until the pull request gets merged.

**Comment by micahjsmith** [comment] 2020-02-04 04:36
Thanks for the report!

Looks like this was caused by the API change in https://github.com/JuliaTime/TimeZones.jl/commit/6401f808c1d79618904d2608ddfa65f3ec7459db#diff-9bc274dbfe972452e9acafe692c9fd38 which removed the `DateTime(::ZonedDateTime) -> DateTime` conversion method

**Comment by micahjsmith** [comment] 2020-02-04 19:03
Closed by #17

**Closed by micahjsmith** 2020-02-04 19:03 UTC
Labels: bug

**Comment by micahjsmith** [comment] 2020-02-08 15:05
@Herold1989 @fratrik Version v0.4.0 with this bugfix has been released on the registry, please try to upgrade and confirm everything works for you!

**Comment by Herold1989** [comment] 2020-02-08 18:28
I checked both before and after updating to the new release. Worked flawless! Thanks for solving this issue so timely!
